# Generated by Django 3.1.1 on 2020-10-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publica', '0002_auto_20201022_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='body',
            field=models.TextField(default='Projeto sem descrição'),
        ),
        migrations.AlterField(
            model_name='project',
            name='funders',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
