# Generated by Django 3.1.1 on 2020-10-27 20:57

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publica', '0004_auto_20201023_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=250, populate_from='title', unique_for_date='start'),
        ),
        migrations.AlterField(
            model_name='publica',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, unique_for_date='publish'),
        ),
        migrations.AlterField(
            model_name='publica',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
