# Generated by Django 3.1.1 on 2020-10-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publica', '0005_auto_20201027_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='start'),
        ),
    ]
