# Generated by Django 3.1.1 on 2020-10-29 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publica', '0006_auto_20201027_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publica',
            name='sec_author',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
