# Generated by Django 3.1.1 on 2020-10-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publica', '0007_auto_20201029_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='publica',
            name='journal',
            field=models.CharField(default='Publicação interna', max_length=250),
        ),
        migrations.AddField(
            model_name='publica',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
