# Generated by Django 3.1.1 on 2020-10-30 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publica', '0008_auto_20201030_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publica',
            name='sec_author',
        ),
    ]
