# Generated by Django 3.1.1 on 2020-11-05 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publica', '0010_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='author',
            name='university',
            field=models.ForeignKey(default='11000', on_delete=django.db.models.deletion.PROTECT, to='publica.university'),
        ),
    ]
