# Generated by Django 3.1.1 on 2020-11-05 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publica', '0011_auto_20201105_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('slug', models.SlugField(default='default-slug', max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='university',
        ),
        migrations.DeleteModel(
            name='University',
        ),
        migrations.AddField(
            model_name='author',
            name='organization',
            field=models.ForeignKey(default='11000', on_delete=django.db.models.deletion.PROTECT, to='publica.organization'),
        ),
    ]
