# Generated by Django 3.1.1 on 2020-11-10 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publica', '0012_auto_20201105_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('researchgate', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('lattes', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='slug',
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='researcher',
            name='organization',
            field=models.ForeignKey(default='11000', on_delete=django.db.models.deletion.PROTECT, to='publica.organization'),
        ),
        migrations.AddField(
            model_name='publica',
            name='researchers',
            field=models.ManyToManyField(to='publica.Researcher'),
        ),
    ]
