# Generated by Django 3.1.1 on 2020-11-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publica', '0013_auto_20201110_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='organization',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
