# Generated by Django 3.1.1 on 2020-11-12 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publica', '0015_researcher_organiztion_abre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researcher',
            old_name='organiztion_abre',
            new_name='organization_abre',
        ),
    ]
