# Generated by Django 3.1.1 on 2020-12-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publica', '0016_auto_20201112_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='publica',
            name='abstract',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='publica',
            name='graphical_abstract',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
