# Generated by Django 3.1.1 on 2020-12-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publica', '0017_auto_20201209_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publica',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publica',
            name='graphical_abstract',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
